#!/usr/bin/env bash
. env.sh

$TXS custom/t_create_set.cdc "Genesis"
$TXS custom/t_create_set.cdc "Base Set"
$TXS custom/t_create_set.cdc "Platinum Ice"
$TXS custom/t_create_set.cdc "Holo MMXX"
$TXS custom/t_create_set.cdc "Metallic Gold LE"
$TXS custom/t_create_set.cdc "Early Adopters"
$TXS custom/t_create_set.cdc "Rookie Debut"
$TXS custom/t_create_set.cdc "Cosmic"
$TXS custom/t_create_set.cdc "For the Win"
$TXS custom/t_create_set.cdc "Denied!"
$TXS custom/t_create_set.cdc "Throwdowns"
$TXS custom/t_create_set.cdc "From the Top"
$TXS custom/t_create_set.cdc "With the Strip"
$TXS custom/t_create_set.cdc "Hometown Showdown: Cali vs. NY"
$TXS custom/t_create_set.cdc "So Fresh"
$TXS custom/t_create_set.cdc "First Round"
$TXS custom/t_create_set.cdc "Conference Semifinals"
$TXS custom/t_create_set.cdc "Western Conference Finals"
$TXS custom/t_create_set.cdc "Eastern Conference Finals"
$TXS custom/t_create_set.cdc "2020 NBA Finals"
$TXS custom/t_create_set.cdc "The Finals"
$TXS custom/t_create_set.cdc "Got Game"
$TXS custom/t_create_set.cdc "Lace 'Em Up"
$TXS custom/t_create_set.cdc "MVP Moves"
$TXS custom/t_create_set.cdc "Run It Back"
$TXS custom/t_create_set.cdc "Base Set"
$TXS custom/t_create_set.cdc "Platinum Ice"
$TXS custom/t_create_set.cdc "Holo Icon"
$TXS custom/t_create_set.cdc "Metallic Gold LE"
$TXS custom/t_create_set.cdc "Season Tip-off"
$TXS custom/t_create_set.cdc "Deck the Hoops"
$TXS custom/t_create_set.cdc "Cool Cats"
$TXS custom/t_create_set.cdc "The Gift"
$TXS custom/t_create_set.cdc "Seeing Stars"
$TXS custom/t_create_set.cdc "Rising Stars"
$TXS custom/t_create_set.cdc "2021 All-Star Game"
$TXS custom/t_create_set.cdc "Hustle and Show"
$TXS custom/t_create_set.cdc "Throwdowns"
$TXS custom/t_create_set.cdc "2021 NBA Playoffs"
$TXS custom/t_create_set.cdc "And Then There Were Four"
$TXS custom/t_create_set.cdc "2021 NBA Finals"
$TXS custom/t_create_set.cdc "Platinum Ice"
$TXS custom/t_create_set.cdc "Summer of '21"
$TXS custom/t_create_set.cdc "WNBA: Best of 2021"
$TXS custom/t_create_set.cdc "WNBA 2021"
$TXS custom/t_create_set.cdc "WNBA Run It Back"

