s/0xFLOWFEES/"FlowFees.cdc"/g
s/0xFLOWTOKEN/"FlowToken.cdc"/g
s/0xFUNGIBLETOKEN/"FungibleToken.cdc"/g
s/0xNONFUNGIBLETOKEN/"NonFungibleToken.cdc"/g
s/0xFTPATHMAPPER/"FtPathMapper.cdc"/g
s/0xCOMMONFEE/"CommonFee.cdc"/g
s/0xNFTPLUS/"NFTPlus.cdc"/g
s/0xNFTSTOREFRONT/"NFTStorefront.cdc"/g
s/0xCOMMONNFT/"CommonNFT.cdc"/g
