#!/usr/bin/env bash
. env.sh

$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Genesis"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Base Set"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Platinum Ice"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Holo MMXX"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Metallic Gold LE"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Early Adopters"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Rookie Debut"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Cosmic"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "For the Win"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Denied!"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Throwdowns"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "From the Top"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "With the Strip"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Hometown Showdown: Cali vs. NY"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "So Fresh"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "First Round"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Conference Semifinals"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Western Conference Finals"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Eastern Conference Finals"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "2020 NBA Finals"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "The Finals"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Got Game"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Lace 'Em Up"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "MVP Moves"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Run It Back"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Base Set"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Platinum Ice"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Holo Icon"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Metallic Gold LE"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Season Tip-off"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Deck the Hoops"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Cool Cats"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "The Gift"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Seeing Stars"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Rising Stars"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "2021 All-Star Game"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Hustle and Show"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Throwdowns"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "2021 NBA Playoffs"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "And Then There Were Four"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "2021 NBA Finals"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Platinum Ice"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "Summer of '21"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "WNBA: Best of 2021"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "WNBA 2021"
$TX $tpservice transactions/custom/topshot/t_create_set.cdc "WNBA Run It Back"

