#!/usr/bin/env bash
. env.sh

$TXS transactions/commonNft/mint.cdc --args-json '[{"type":"String","value":"url://"},{"type":"Array","value":[{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$EVE"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.02"}}]}},{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$SERVICE"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.05"}}]}}]}]'
$TXS transactions/commonNft/mint.cdc --args-json '[{"type":"String","value":"url://"},{"type":"Array","value":[{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$BOB"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.02"}}]}},{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$EVE"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.05"}}]}}]}]'

$TX $alice transactions/commonNft/mint.cdc --args-json '[{"type":"String","value":"url://"},{"type":"Array","value":[{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$BOB"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.02"}}]}},{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$EVE"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.05"}}]}}]}]'
$TX $alice transactions/commonNft/mint.cdc --args-json '[{"type":"String","value":"url://"},{"type":"Array","value":[{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$BOB"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.02"}}]}},{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$EVE"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.05"}}]}}]}]'

$TX $bob transactions/commonNft/mint.cdc --args-json '[{"type":"String","value":"url://"},{"type":"Array","value":[{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$BOB"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.02"}}]}},{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$EVE"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.05"}}]}}]}]'
$TX $bob transactions/commonNft/mint.cdc --args-json '[{"type":"String","value":"url://"},{"type":"Array","value":[{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$BOB"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.02"}}]}},{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$EVE"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.05"}}]}}]}]'

$TX $eve transactions/commonNft/mint.cdc --args-json '[{"type":"String","value":"url://"},{"type":"Array","value":[{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$BOB"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.02"}}]}},{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$EVE"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.05"}}]}}]}]'
$TX $eve transactions/commonNft/mint.cdc --args-json '[{"type":"String","value":"url://"},{"type":"Array","value":[{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$BOB"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.02"}}]}},{"type":"Struct","value":{"id":"A.'"$CONTRACT"'.CommonNFT.Royalty","fields":[{"name":"address","value":{"type":"Address","value":"'"$EVE"'"}},{"name":"fee","value":{"type":"UFix64","value":"0.05"}}]}}]}]'
